POST http://localhost:5000/project/add
content-type: application/json

{
    "title": "Half Life 3",
    "users": [
        {"userId": "606b5ae022f56faeb6ab693b", "role": "Team Leader"}
    ],
    "tasks":[
        {
            "taskKey": "T1",
            "title": "Level 1 Glitch",
            "description": "Graphical glitch at start of level 1",
            "type": "Bug",
            "assignee": "606b5ae022f56faeb6ab693b",
            "reporter": "6074b91a80b41682a78f680d",
            "status": "In Progress",
            "resolution": "Unresolved",
            "dateCreated": "21-02-2021",
            "dateUpdated": "01-04-2021",
            "comments": [
                {
                    "content": "This is a comment on task T1 in the Half Life 3 project",
                    "taggedUsers":["6074b91a80b41682a78f680d"]
                }
            ],
            "subtasks": []
        }
    ]
}

####

POST http://localhost:5000/project/add
content-type: application/json

{
    "title": "Flappy Bird 2",
    "users": [
        {"userId": "606b5ae022f56faeb6ab693b", "role": "Team Leader"}
    ],
    "tasks":[]
}

####

POST http://localhost:5000/project/add
content-type: application/json

{
    "title": "Half Life 3",
    "users": [
        {"userId": "606b5ae022f56faeb6ab693b", "role": "Team Leader"}
    ]
}


###
GET http://localhost:5000/project/6074d4691477622b950de63a
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliMjQ2ODI3MjY3ZDJmOWVlM2RmYjUiLCJpYXQiOjE2MjA3ODA0ODd9.8NNg5yWuLrSULNy44O33D9xjjXh6GuSTbftV0SGpEkk

###
GET http://localhost:5000/project/606b955a35d1b7d715262273


###
GET http://localhost:5000/user/allprojects
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliMjQ2ODI3MjY3ZDJmOWVlM2RmYjUiLCJpYXQiOjE2MjA3ODA0ODd9.8NNg5yWuLrSULNy44O33D9xjjXh6GuSTbftV0SGpEkk

###
POST http://localhost:5000/user/register
content-type: application/json

{
    "firstName": "David",
    "lastName": "Cottrell",
    "email": "davidjamescottrell@gmail.com",
    "password": "password",
    "projects": [
        {"_id": "6074d4691477622b950de63a"}
    ]
}

###
POST http://localhost:5000/user/register
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "password": "password123"
}

###
POST http://localhost:5000/user/register
content-type: application/json

{
    "firstName": "Edward",
    "lastName": "Smith",
    "email": "edsmith@gmail.com",
    "password": "password123"
}

###
POST http://localhost:5000/user/login
content-type: application/json

{
    "email": "davidjamescottrell@gmail.com",
    "password": "password"
}

###
POST http://localhost:5000/user/login
content-type: application/json

{
    "email": "edsmith@gmail.com",
    "password": "password123"
}

###
POST http://localhost:5000/user/login
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "password123"
}

# Add task to project

# Add user to project