# Create Half Life 3 Project
POST http://localhost:5000/project/add
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliMjQ2ODI3MjY3ZDJmOWVlM2RmYjUiLCJpYXQiOjE2MjA4MjU3MzR9.hwyCkykkAQUi_dabgm8XUiKzwXrrgN-ONfUGS_1oHXM
content-type: application/json

{
    "title": "Half Life 3",
    "users": [
        {"userId": "609b246827267d2f9ee3dfb5", "role": "Team Leader"}
    ],
    "tasks":[
        {
            "taskKey": "T1",
            "title": "Level 1 Glitch",
            "description": "Graphical glitch at start of level 1",
            "type": "Bug",
            "assignee": "606b5ae022f56faeb6ab693b",
            "reporter": "6074b91a80b41682a78f680d",
            "status": "In Progress",
            "resolution": "Unresolved",
            "dateCreated": "21-02-2021",
            "dateUpdated": "01-04-2021",
            "comments": [
                {
                    "content": "This is a comment on task T1 in the Half Life 3 project",
                    "taggedUsers":["6074b91a80b41682a78f680d"]
                }
            ],
            "subtasks": []
        }
    ]
}