####
# Create Half Life 3 project
POST http://localhost:5000/project/add
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliZjBmMjBjNjM4YjQ2YjJhNWEyNjUiLCJpYXQiOjE2MjA4MzI1MTF9.VzS3BfKHq023GmDqKV9ODQDypVdmYha9S-hUL813ms4
content-type: application/json

{
    "title": "Half Life 3",
    "users": [],
    "tasks":[]
}

####
# Create Fallout 3 project
POST http://localhost:5000/project/add
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliZjBmYTBjNjM4YjQ2YjJhNWEyNjYiLCJpYXQiOjE2MjA4MzI1MTl9.tGX-au2mWYlOBUrbZHOe9ED1s0QRjf2VUBjk7U6a7GI
content-type: application/json

{
    "title": "Fallout 3",
    "users": [],
    "tasks":[]
}

####
# Create Club Penguin Project
POST http://localhost:5000/project/add
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliZjBmYTBjNjM4YjQ2YjJhNWEyNjYiLCJpYXQiOjE2MjA4MzI1MTl9.tGX-au2mWYlOBUrbZHOe9ED1s0QRjf2VUBjk7U6a7GI
content-type: application/json

{
    "title": "Club Penguin",
    "users": [
        {"userId": "609bd61sssseee33", "role": "Team Leader"}
    ],
    "tasks":[]
}



###
# Get a specific project if authed
GET http://localhost:5000/project/6074d4691477622b950de63a
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliMjQ2ODI3MjY3ZDJmOWVlM2RmYjUiLCJpYXQiOjE2MjA4MjU3MzR9.hwyCkykkAQUi_dabgm8XUiKzwXrrgN-ONfUGS_1oHXM



# Add tasks to a project
