# Get all project related to the user whos token is passed
GET http://localhost:9000/user/projects
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDliZjBmMjBjNjM4YjQ2YjJhNWEyNjUiLCJpYXQiOjE2MjA4MzI1MTF9.VzS3BfKHq023GmDqKV9ODQDypVdmYha9S-hUL813ms4

###
# Add project to user with provided token
PATCH http://localhost:9000/user/addproject/617eed598d381b0a66c8f91c
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdlZWE5NDBhMDRiYTA4NzUzZGE3M2UiLCJpYXQiOjE2MzU3MDgzNDR9.4nGHfd0Cdn7sAdqdNiUhwUDCNmlWxwzaqm8TG_P1biA


###
# David Cottrell register
POST http://localhost:9000/user/register 
content-type: application/json

{
    "firstName": "David",
    "lastName": "Cottrell",
    "email": "davidjamescottrell@gmail.com",
    "password": "password123"
}

###
# Edward Smith register
POST http://localhost:9000/user/register
content-type: application/json

{
    "firstName": "Edward",
    "lastName": "Smith",
    "email": "edsmith@gmail.com",
    "password": "password123"
}

###
# David Cottrell login
POST http://localhost:9000/user/login
content-type: application/json

{
    "email": "davidjamescottrell@gmail.com",
    "password": "password123"
}


###
# Edward Smith login
POST http://localhost:9000/user/login
content-type: application/json

{
    "email": "edsmith@gmail.com",
    "password": "password123"
}