# Get all project related to the user whos token is passed
GET http://localhost:9000/user/projects
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdlZWQ0NThkMzgxYjBhNjZjOGY5MWIiLCJpYXQiOjE2NDI1MzE5Mjh9.-VOqiZnNlXIeZUF6eE_1AwJzR4DVavYXhwXbKK8v7qM

###
# Add project to user with provided token
PATCH http://localhost:9000/user/addproject/61bf1a8d95debb804851586a
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdlZWQ0NThkMzgxYjBhNjZjOGY5MWIiLCJpYXQiOjE2Mzk5MTE3MTh9.GXXj6DdqoMQA8NOx5bM6t4p9Xy6KytqW9DkCwP3RrW4

###
# Get user details based on token
GET http://localhost:9000/user/details
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdlZWQ0NThkMzgxYjBhNjZjOGY5MWIiLCJpYXQiOjE2NDAwMzU2ODN9.7n2SpvsEdBpaIvheZK7q-kWJSiz-CX6M3XnguTfGGFk



###
# David Cottrell register
POST http://localhost:9000/user/register 
content-type: application/json

{
    "firstName": "David",
    "lastName": "Cottrell",
    "email": "davidjamescottrell@gmail.com",
    "password": "password123"
}

###
# Edward Smith register
POST http://localhost:9000/user/register
content-type: application/json

{
    "firstName": "Edward",
    "lastName": "Smith",
    "email": "edsmith@gmail.com",
    "password": "password123"
}

###
# David Cottrell login
POST http://localhost:9000/user/login
content-type: application/json

{
    "email": "davidjamescottrell@gmail.com",
    "password": "password123"
}


###
# Edward Smith login
POST http://localhost:9000/user/login
content-type: application/json

{
    "email": "edsmith@gmail.com",
    "password": "password123"
}